# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2ef485839492b30f1b12fa2ada2ebb3488d4b73973aa6efd1398e2c6aed9dfb30187fa094909c2d258958624f07f107528ef8847aeff9e81553088b1d66d61a

test:
  secret_key_base: f5767d66b30889e9664621a3509b2b68a6c7a001d744c5a7c81d4437f96f9f86b012d8d4a696bfa278049b98dad40e172f797167e136c5dfd42752086b3b03e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
